version: "3.8"
services:
  postgres:
    image: postgres:14.0-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=C0V1D19
      - POSTGRES_DB=complex_db
    volumes:
      - ./data/db:/var/lib/postgresql/data/

  redis:
    image: redis:6.2.6-alpine

  api:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=root
      - PGPASSWORD=C0V1D19
      - PGDATABASE=complex_db
      - PGHOST=postgres
      - PGPORT=5432

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile.dev
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - /app/node_modules
      - ./worker:/app

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./client:/app    

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - "3030:80"
    restart: always